"""initial migration

Revision ID: ca3bbb681837
Revises: 
Create Date: 2025-02-19 13:13:24.532742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3bbb681837'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afiliados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('afiliados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_afiliados_dni'), ['dni'], unique=True)
        batch_op.create_index(batch_op.f('ix_afiliados_numero'), ['numero'], unique=True)

    op.create_table('operaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('nombre1', sa.String(length=50), nullable=False),
    sa.Column('nombre2', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operaciones_fecha'), ['fecha'], unique=False)

    op.create_table('rango_afiliados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_afiliado', sa.String(length=50), nullable=False),
    sa.Column('rango_inicio', sa.Float(), nullable=False),
    sa.Column('rango_fin', sa.Float(), nullable=False),
    sa.Column('recibe_en', sa.String(length=20), nullable=False),
    sa.Column('envia_a', sa.String(length=20), nullable=False),
    sa.CheckConstraint("envia_a IN ('Izipay', 'Iziya', 'Ambos')", name='check_envia_a'),
    sa.CheckConstraint("recibe_en IN ('Izipay', 'Iziya', 'Ambos')", name='check_recibe_en'),
    sa.ForeignKeyConstraint(['numero_afiliado'], ['afiliados.numero'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rango_afiliados', schema=None) as batch_op:
        batch_op.create_index('idx_rango_afiliados_rangos', ['rango_inicio', 'rango_fin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rango_afiliados', schema=None) as batch_op:
        batch_op.drop_index('idx_rango_afiliados_rangos')

    op.drop_table('rango_afiliados')
    with op.batch_alter_table('operaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operaciones_fecha'))

    op.drop_table('operaciones')
    with op.batch_alter_table('afiliados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_afiliados_numero'))
        batch_op.drop_index(batch_op.f('ix_afiliados_dni'))

    op.drop_table('afiliados')
    # ### end Alembic commands ###
